"""Add new items

Revision ID: 39beff4be9c6
Revises: 
Create Date: 2024-01-10 15:18:45.175766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39beff4be9c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    op.execute("INSERT INTO owners (name) VALUES ('Bryson')")

    op.execute("INSERT INTO pets (name, owner_id) VALUES ('kitty', 2)")
    op.execute("INSERT INTO pets (name, owner_id) VALUES ('milo', 2)")

    op.execute("INSERT INTO feeding_training (name) VALUES ('beef and milk')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('owners')
    op.drop_table('feeding_training')
    # ### end Alembic commands ###
