"""Add name column to vets table

Revision ID: ca8a9d82a80a
Revises: fd7069bbdb82
Create Date: 2024-01-11 23:46:37.033583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8a9d82a80a'
down_revision = 'fd7069bbdb82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeding_training')
    op.drop_table('adoptions')
    op.alter_column('vet_visits', 'visit_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(None, 'vet_visits', type_='foreignkey')
    op.drop_column('vet_visits', 'notes')
    op.drop_column('vet_visits', 'pet_id')
    op.drop_column('vet_visits', 'reason')
    op.add_column('vets', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('vets', 'vet_name')
    op.drop_column('vets', 'contact_info')
    op.drop_column('vets', 'vet_specialty')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vets', sa.Column('vet_specialty', sa.VARCHAR(), nullable=True))
    op.add_column('vets', sa.Column('contact_info', sa.VARCHAR(), nullable=True))
    op.add_column('vets', sa.Column('vet_name', sa.VARCHAR(), nullable=False))
    op.drop_column('vets', 'name')
    op.add_column('vet_visits', sa.Column('reason', sa.VARCHAR(), nullable=True))
    op.add_column('vet_visits', sa.Column('pet_id', sa.INTEGER(), nullable=True))
    op.add_column('vet_visits', sa.Column('notes', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'vet_visits', 'pets', ['pet_id'], ['id'])
    op.alter_column('vet_visits', 'visit_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table('adoptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('adoption_date', sa.DATETIME(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeding_training',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
